FROM  nvidia/cuda:12.0.1-cudnn8-devel-ubuntu22.04

RUN apt-get update -y
RUN apt-get install -y git curl python3 python3-pip python3-poetry sudo bash tree

RUN useradd -m user
RUN echo 'user:password' | chpasswd
RUN usermod -aG sudo user
RUN chsh -s /usr/bin/bash user
USER user
